Get http://localhost:5000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNjk4NjIzOTgwfQ.PgWl2EyVd2oGoJ_yQffZ5XESXCDkyNFuhc_gaQzPgu0

###

POST http://localhost:5000/login
Content-Type: application/json

{
  "username": "Jim"
}

